#!/system/bin/sh
mount -o remount,nodiratime,noatime /dev/block/mtdblock4 /system
mount -o remount,nodiratime,noatime /dev/block/mtdblock5 /cache
mount -o remount,nodiratime,noatime /dev/block/mtdblock6 /data
