#!/system/bin/sh
# Automatic ZipAlign originally by Wes Garner
# ZipAlign files in /system that have not been previously ZipAligned
# Thanks to oknowton for the changes

# Changelog:
# 1.2 (1/12/14) ChevyCam94 - Now does apks on /system/ instead of /data.  More in next version
# 1.1 (12/1/09) Switched to zipalign -c 4 to check the apk instead of MD5 (oknowton)
# 1.0 (11/30/09) Original

# Mount system RW
mount -o remount,rw -t yaffs2 /dev/block/mtdblock5 /system

LOG_FILE=/data/zipalign.log
    if [ -e $LOG_FILE ]; then
        rm $LOG_FILE;
    fi;

echo "Starting Automatic ZipAlign $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $LOG_FILE;
    for apk in /system/app/*.apk ; do
    zipalign -c 4 $apk;
    ZIPCHECK=$?;
    if [ $ZIPCHECK -eq 1 ]; then
        echo ZipAligning $(basename $apk)  | tee -a $LOG_FILE;
        zipalign -f 4 $apk /cache/$(basename $apk);
            if [ -e /cache/$(basename $apk) ]; then
                cp -f -p /cache/$(basename $apk) $apk  | tee -a $LOG_FILE;
                rm /cache/$(basename $apk);
            else
                echo ZipAligning $(basename $apk) Failed  | tee -a $LOG_FILE;
            fi;
    else
        echo ZipAlign already completed on $apk  | tee -a $LOG_FILE;
    fi;
       done;
echo "Automatic ZipAlign finished at $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $LOG_FILE;

# Mount system RO
mount -o remount,ro -t yaffs2 /dev/block/mtdblock5 /system
